// verbos.js - Base de datos completa
// Usamos 'window' para asegurar visibilidad global
window.verbosIrregulares = [
  { "id": 1, "presente": "arise", "pasado": "arose", "participio": "arisen", "espanol": "surgir" },
  { "id": 2, "presente": "be", "pasado": "was/were", "participio": "been", "espanol": "ser" },
  { "id": 3, "presente": "beat", "pasado": "beat", "participio": "beaten", "espanol": "golpear" },
  { "id": 4, "presente": "become", "pasado": "became", "participio": "become", "espanol": "convertirse" },
  { "id": 5, "presente": "begin", "pasado": "began", "participio": "begun", "espanol": "comenzar" },
  { "id": 6, "presente": "bet", "pasado": "bet/betted", "participio": "bet/betted", "espanol": "apostar" },
  { "id": 7, "presente": "bite", "pasado": "bit", "participio": "bitten", "espanol": "morder" },
  { "id": 8, "presente": "bleed", "pasado": "bled", "participio": "bled", "espanol": "sangrar" },
  { "id": 9, "presente": "blow", "pasado": "blew", "participio": "blown", "espanol": "soplar" },
  { "id": 10, "presente": "break", "pasado": "broke", "participio": "broken", "espanol": "romper" },
  { "id": 11, "presente": "bring", "pasado": "brought", "participio": "brought", "espanol": "traer" },
  { "id": 12, "presente": "build", "pasado": "built", "participio": "built", "espanol": "construir" },
  { "id": 13, "presente": "buy", "pasado": "bought", "participio": "bought", "espanol": "comprar" },
  { "id": 14, "presente": "catch", "pasado": "caught", "participio": "caught", "espanol": "atrapar" },
  { "id": 15, "presente": "choose", "pasado": "chose", "participio": "chosen", "espanol": "elegir" },
  { "id": 16, "presente": "come", "pasado": "came", "participio": "come", "espanol": "venir" },
  { "id": 17, "presente": "cost", "pasado": "cost", "participio": "cost", "espanol": "costar" },
  { "id": 18, "presente": "creep", "pasado": "crept", "participio": "crept", "espanol": "arrastrarse" },
  { "id": 19, "presente": "cut", "pasado": "cut", "participio": "cut", "espanol": "cortar" },
  { "id": 20, "presente": "deal", "pasado": "dealt", "participio": "dealt", "espanol": "dar, repartir" },
  { "id": 21, "presente": "do", "pasado": "did", "participio": "done", "espanol": "hacer" },
  { "id": 22, "presente": "draw", "pasado": "drew", "participio": "drawn", "espanol": "dibujar" },
  { "id": 23, "presente": "dream", "pasado": "dreamt/dreamed", "participio": "dreamt/dreamed", "espanol": "soñar" },
  { "id": 24, "presente": "drink", "pasado": "drank", "participio": "drunk", "espanol": "beber" },
  { "id": 25, "presente": "drive", "pasado": "drove", "participio": "driven", "espanol": "conducir" },
  { "id": 26, "presente": "eat", "pasado": "ate", "participio": "eaten", "espanol": "comer" },
  { "id": 27, "presente": "fall", "pasado": "fell", "participio": "fallen", "espanol": "caer" },
  { "id": 28, "presente": "feed", "pasado": "fed", "participio": "fed", "espanol": "alimentar" },
  { "id": 29, "presente": "feel", "pasado": "felt", "participio": "felt", "espanol": "sentir" },
  { "id": 30, "presente": "fight", "pasado": "fought", "participio": "fought", "espanol": "pelear" },
  { "id": 31, "presente": "find", "pasado": "found", "participio": "found", "espanol": "encontrar" },
  { "id": 32, "presente": "flee", "pasado": "fled", "participio": "fled", "espanol": "huir" },
  { "id": 33, "presente": "fly", "pasado": "flew", "participio": "flown", "espanol": "volar" },
  { "id": 34, "presente": "forget", "pasado": "forgot", "participio": "forgotten", "espanol": "olvidar" },
  { "id": 35, "presente": "forgive", "pasado": "forgave", "participio": "forgiven", "espanol": "perdonar" },
  { "id": 36, "presente": "forsake", "pasado": "forsook", "participio": "forsaken", "espanol": "abandonar" },
  { "id": 37, "presente": "freeze", "pasado": "froze", "participio": "frozen", "espanol": "congelar" },
  { "id": 38, "presente": "get", "pasado": "got", "participio": "got", "espanol": "tener, obtener" },
  { "id": 39, "presente": "give", "pasado": "gave", "participio": "given", "espanol": "dar" },
  { "id": 40, "presente": "go", "pasado": "went", "participio": "gone", "espanol": "ir" },
  { "id": 41, "presente": "grind", "pasado": "ground", "participio": "ground", "espanol": "moler" },
  { "id": 42, "presente": "grow", "pasado": "grew", "participio": "grown", "espanol": "crecer" },
  { "id": 43, "presente": "hang", "pasado": "hung", "participio": "hung", "espanol": "colgar" },
  { "id": 44, "presente": "have", "pasado": "had", "participio": "had", "espanol": "tener" },
  { "id": 45, "presente": "hear", "pasado": "heard", "participio": "heard", "espanol": "oír" },
  { "id": 46, "presente": "hide", "pasado": "hid", "participio": "hidden", "espanol": "esconderse" },
  { "id": 47, "presente": "hit", "pasado": "hit", "participio": "hit", "espanol": "golpear" },
  { "id": 48, "presente": "hold", "pasado": "held", "participio": "held", "espanol": "tener, mantener" },
  { "id": 49, "presente": "hurt", "pasado": "hurt", "participio": "hurt", "espanol": "herir, doler" },
  { "id": 50, "presente": "keep", "pasado": "kept", "participio": "kept", "espanol": "guardar" },
  { "id": 51, "presente": "kneel", "pasado": "knelt", "participio": "knelt", "espanol": "arrodillarse" },
  { "id": 52, "presente": "know", "pasado": "knew", "participio": "known", "espanol": "saber" },
  { "id": 53, "presente": "lead", "pasado": "led", "participio": "led", "espanol": "encabezar" },
  { "id": 54, "presente": "learn", "pasado": "learnt/learned", "participio": "learnt/learned", "espanol": "aprender" },
  { "id": 55, "presente": "leave", "pasado": "left", "participio": "left", "espanol": "dejar" },
  { "id": 56, "presente": "lend", "pasado": "lent", "participio": "lent", "espanol": "prestar" },
  { "id": 57, "presente": "let", "pasado": "let", "participio": "let", "espanol": "dejar" },
  { "id": 58, "presente": "lie", "pasado": "lay", "participio": "lain", "espanol": "yacer" },
  { "id": 59, "presente": "lose", "pasado": "lost", "participio": "lost", "espanol": "perder" },
  { "id": 60, "presente": "make", "pasado": "made", "participio": "made", "espanol": "hacer" },
  { "id": 61, "presente": "mean", "pasado": "meant", "participio": "meant", "espanol": "significar" },
  { "id": 62, "presente": "meet", "pasado": "met", "participio": "met", "espanol": "conocer, encontrar" },
  { "id": 63, "presente": "pay", "pasado": "paid", "participio": "paid", "espanol": "pagar" },
  { "id": 64, "presente": "put", "pasado": "put", "participio": "put", "espanol": "poner" },
  { "id": 65, "presente": "quit", "pasado": "quit/quitted", "participio": "quit/quitted", "espanol": "abandonar" },
  { "id": 66, "presente": "read", "pasado": "read", "participio": "read", "espanol": "leer" },
  { "id": 67, "presente": "ride", "pasado": "rode", "participio": "ridden", "espanol": "montar, ir" },
  { "id": 68, "presente": "ring", "pasado": "rang", "participio": "rung", "espanol": "llamar por teléfono" },
  { "id": 69, "presente": "rise", "pasado": "rose", "participio": "risen", "espanol": "elevar" },
  { "id": 70, "presente": "run", "pasado": "ran", "participio": "run", "espanol": "correr" },
  { "id": 71, "presente": "say", "pasado": "said", "participio": "said", "espanol": "decir" },
  { "id": 72, "presente": "see", "pasado": "saw", "participio": "seen", "espanol": "ver" },
  { "id": 73, "presente": "sell", "pasado": "sold", "participio": "sold", "espanol": "vender" },
  { "id": 74, "presente": "send", "pasado": "sent", "participio": "sent", "espanol": "enviar" },
  { "id": 75, "presente": "set", "pasado": "set", "participio": "set", "espanol": "fijar" },
  { "id": 76, "presente": "sew", "pasado": "sewed", "participio": "sewn/sewed", "espanol": "coser" },
  { "id": 77, "presente": "shake", "pasado": "shook", "participio": "shaken", "espanol": "sacudir" },
  { "id": 78, "presente": "shine", "pasado": "shone", "participio": "shone", "espanol": "brillar" },
  { "id": 79, "presente": "shoot", "pasado": "shot", "participio": "shot", "espanol": "disparar" },
  { "id": 80, "presente": "show", "pasado": "showed", "participio": "shown/showed", "espanol": "mostrar" },
  { "id": 81, "presente": "shrink", "pasado": "shrank/shrunk", "participio": "shrunk", "espanol": "encoger" },
  { "id": 82, "presente": "shut", "pasado": "shut", "participio": "shut", "espanol": "cerrar" },
  { "id": 83, "presente": "sing", "pasado": "sang", "participio": "sung", "espanol": "cantar" },
  { "id": 84, "presente": "sink", "pasado": "sank", "participio": "sunk", "espanol": "hundir" },
  { "id": 85, "presente": "sit", "pasado": "sat", "participio": "sat", "espanol": "sentarse" },
  { "id": 86, "presente": "sleep", "pasado": "slept", "participio": "slept", "espanol": "dormir" },
  { "id": 87, "presente": "slide", "pasado": "slid", "participio": "slid", "espanol": "deslizar" },
  { "id": 88, "presente": "sow", "pasado": "sowed", "participio": "sown/sowed", "espanol": "sembrar" },
  { "id": 89, "presente": "speak", "pasado": "spoke", "participio": "spoken", "espanol": "hablar" },
  { "id": 90, "presente": "spell", "pasado": "spelt/spelled", "participio": "spelt/spelled", "espanol": "deletrear" },
  { "id": 91, "presente": "spend", "pasado": "spent", "participio": "spent", "espanol": "gastar" },
  { "id": 92, "presente": "spill", "pasado": "spilt/spilled", "participio": "spilt/spilled", "espanol": "derramar" },
  { "id": 93, "presente": "split", "pasado": "split", "participio": "split", "espanol": "partir" },
  { "id": 94, "presente": "spoil", "pasado": "spoilt/spoiled", "participio": "spoilt/spoiled", "espanol": "estropear" },
  { "id": 95, "presente": "spread", "pasado": "spread", "participio": "spread", "espanol": "extenderse" },
  { "id": 96, "presente": "stand", "pasado": "stood", "participio": "stood", "espanol": "estar de pie" },
  { "id": 97, "presente": "steal", "pasado": "stole", "participio": "stolen", "espanol": "robar" },
  { "id": 98, "presente": "sting", "pasado": "stung", "participio": "stung", "espanol": "picar" },
  { "id": 99, "presente": "stink", "pasado": "stank/stunk", "participio": "stunk", "espanol": "apestar" },
  { "id": 100, "presente": "strike", "pasado": "struck", "participio": "struck", "espanol": "golpear" },
  { "id": 101, "presente": "swear", "pasado": "swore", "participio": "sworn", "espanol": "jurar" },
  { "id": 102, "presente": "sweep", "pasado": "swept", "participio": "swept", "espanol": "barrer" },
  { "id": 103, "presente": "swim", "pasado": "swam", "participio": "swum", "espanol": "nadar" },
  { "id": 104, "presente": "take", "pasado": "took", "participio": "taken", "espanol": "tomar" },
  { "id": 105, "presente": "teach", "pasado": "taught", "participio": "taught", "espanol": "enseñar" },
  { "id": 106, "presente": "tear", "pasado": "tore", "participio": "torn", "espanol": "romper" },
  { "id": 107, "presente": "tell", "pasado": "told", "participio": "told", "espanol": "decir" },
  { "id": 108, "presente": "think", "pasado": "thought", "participio": "thought", "espanol": "pensar" },
  { "id": 109, "presente": "throw", "pasado": "threw", "participio": "thrown", "espanol": "lanzar" },
  { "id": 110, "presente": "tread", "pasado": "trode", "participio": "trodden/trod", "espanol": "pisar" },
  { "id": 111, "presente": "understand", "pasado": "understood", "participio": "understood", "espanol": "entender" },
  { "id": 112, "presente": "wake", "pasado": "woke", "participio": "woken", "espanol": "despertarse" },
  { "id": 113, "presente": "wear", "pasado": "wore", "participio": "worn", "espanol": "llevar puesto" },
  { "id": 114, "presente": "weave", "pasado": "wove", "participio": "woven", "espanol": "tejer" },
  { "id": 115, "presente": "weep", "pasado": "wept", "participio": "wept", "espanol": "llorar" },
  { "id": 116, "presente": "win", "pasado": "won", "participio": "won", "espanol": "ganar" },
  { "id": 117, "presente": "wring", "pasado": "wrung", "participio": "wrung", "espanol": "retorcer" },
  { "id": 118, "presente": "write", "pasado": "wrote", "participio": "written", "espanol": "escribir" }
];